jobs:
- name: bootstrap
  plan:
    - get: common-pipelines
      trigger: true

    # The container pipeline loads some vars from the concrete pipeline's repository.
    # Must get src here so they are available to set_pipeline below.
    - get: src

    - set_pipeline: self
      file: common-pipelines/container/pipeline.yml
      var_files:
        - src/container/ci/vars.yml

resources:
- name: common-pipelines
  type: git
  source:
    uri: https://github.com/cloud-gov/common-pipelines
    branch: usg-audit
    commit_verification_keys: ((cloud-gov-pgp-keys))

- name: src
  type: git
  source:
    uri: https://github.com/((src-repo))
    branch: test-pr
    commit_verification_keys: ((cloud-gov-pgp-keys))
