jobs:
- name: set-self
  plan:
    - get: common-pipelines
      trigger: true
    - set_pipeline: self
      file: common-pipelines/go/pipeline.yml
      vars:
        src-repo: https://github.com/cloud-gov/use-common-pipelines

resources:
- name: common-pipelines
  type: git
  source:
    uri: https://github.com/cloud-gov/common-pipelines
    branch: testing
    commit_verification_keys: ((cloud-gov-pgp-keys))
